name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_ENV        
        mkdir ./target
        mkdir ./release
        curl -L https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb -o ./target/Country.mmdb
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./target/ip2country -v .
        tar czvf ./release/ip2country_linux.tgz ./target/*
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./target/ip2country -v .
        tar czvf ./release/ip2country_mac.tgz ./target/*
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./target/ip2country -v .
        tar czvf ./release/ip2country_win.tgz ./target/*

    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./release/*
        tag: ${{env.strDate}}
        file_glob: true
        overwrite: true
        release_name: ${{env.strDate}} 自动发布